/* Auto-generated by build.py from PRICE_CATEGORIES — do not edit by hand. */
window.N2W_PRICES = {
  "from": 15,
  "phone": "07521 349799",
  "tel": "+447521349799",
  "email": "notime2wasteplym@gmail.com",
  "depositPercent": 20,
  "bank": {
    "name": "No Time 2 Waste",
    "sort": "04-06-05",
    "account": "25897642"
  },
  "hours": {
    "1": {
      "open": "08:00",
      "close": "16:00"
    },
    "2": {
      "open": "08:00",
      "close": "16:00"
    },
    "3": {
      "open": "08:00",
      "close": "16:00"
    },
    "4": {
      "open": "08:00",
      "close": "16:00"
    },
    "5": {
      "open": "08:00",
      "close": "16:00"
    },
    "6": {
      "open": "08:00",
      "close": "16:00"
    },
    "0": {
      "open": "08:00",
      "close": "16:00"
    }
  },
  "hoursHuman": "Open 7 days · 8am–4pm",
  "bookingWindow": {
    "open": "09:00",
    "close": "15:00"
  },
  "categories": [
    {
      "id": "mixed-household",
      "name": "Mixed Household",
      "blurb": "General mixed rubbish by the van load — the easiest option for most homes.",
      "items": [
        {
          "name": "Mixed Waste 250kg (¼ van approx)",
          "mins": 30,
          "price": 100
        },
        {
          "name": "Mixed Waste 500kg (½ van approx)",
          "mins": 45,
          "price": 200
        },
        {
          "name": "Mixed Waste 1 Tonne (full van)",
          "mins": 45,
          "price": 400
        }
      ]
    },
    {
      "id": "small-items",
      "name": "Small Items",
      "blurb": "Single small household items and small appliances.",
      "items": [
        {
          "name": "Washing Machine",
          "mins": 20,
          "price": 20
        },
        {
          "name": "Cooker",
          "mins": 20,
          "price": 20
        },
        {
          "name": "Coffee Table / Bedside Table",
          "mins": 20,
          "price": 20
        },
        {
          "name": "TV – up to 40\"",
          "mins": 20,
          "price": 25
        },
        {
          "name": "Single Wardrobe",
          "mins": 20,
          "price": 30
        },
        {
          "name": "Bed Frame (single or double) – no divan",
          "mins": 20,
          "price": 30
        },
        {
          "name": "Single Armchair",
          "mins": 20,
          "price": 30
        },
        {
          "name": "Double Mattress",
          "mins": 20,
          "price": 30
        },
        {
          "name": "Up to 8 Black Sacks",
          "mins": 20,
          "price": 40
        }
      ]
    },
    {
      "id": "medium-items",
      "name": "Medium Items",
      "blurb": "Larger single items and bigger furniture.",
      "items": [
        {
          "name": "TV – 41\"+",
          "mins": 30,
          "price": 30
        },
        {
          "name": "Trampoline",
          "mins": 30,
          "price": 30
        },
        {
          "name": "Bed Frame / Divan / King / Queen",
          "mins": 30,
          "price": 40
        },
        {
          "name": "2 / 3 Seat Sofa (non-reclining)",
          "mins": 30,
          "price": 50
        },
        {
          "name": "8–15 Black Sacks",
          "mins": 30,
          "price": 50
        },
        {
          "name": "Double Wardrobe",
          "mins": 30,
          "price": 50
        },
        {
          "name": "Mattress King / Queen",
          "mins": 30,
          "price": 50
        },
        {
          "name": "Fridge / Freezer",
          "mins": 30,
          "price": 60
        }
      ]
    },
    {
      "id": "large-items",
      "name": "Large Items",
      "blurb": "Bulky, heavy or awkward single items.",
      "items": [
        {
          "name": "Fitted Wardrobe / Glass-fronted",
          "mins": 45,
          "price": 60
        },
        {
          "name": "Corner Sofa / Reclining Sofa",
          "mins": 45,
          "price": 60
        },
        {
          "name": "Large Furniture / Dining Table",
          "mins": 45,
          "price": 75
        },
        {
          "name": "Greenhouse",
          "mins": 45,
          "price": 125
        }
      ]
    },
    {
      "id": "wood",
      "name": "Wood",
      "blurb": "Timber, fence panels, decking, pallets and joinery offcuts.",
      "items": [
        {
          "name": "½ Tonne Wood",
          "mins": 45,
          "price": 100
        },
        {
          "name": "1 Tonne Wood",
          "mins": 45,
          "price": 210
        }
      ]
    },
    {
      "id": "shed-garage",
      "name": "Shed / Garage",
      "blurb": "Shed dismantling and removal, plus part or full garage clearances.",
      "items": [
        {
          "name": "Dismantle & Remove Shed – up to 8×6ft",
          "mins": 60,
          "price": 60
        },
        {
          "name": "Dismantle & Remove Shed – 10×8ft +",
          "mins": 60,
          "price": 85
        },
        {
          "name": "½ Shed Clearance",
          "mins": 30,
          "price": 100
        },
        {
          "name": "Whole Shed Removal",
          "mins": 60,
          "price": 200
        },
        {
          "name": "¼ Garage Clearance",
          "mins": 30,
          "price": 150
        },
        {
          "name": "½ Garage Clearance",
          "mins": 60,
          "price": 300
        },
        {
          "name": "Full Garage Removal",
          "mins": 120,
          "price": 600
        }
      ]
    },
    {
      "id": "soil-rubble",
      "name": "Soil / Rubble",
      "blurb": "Heavy soil, hardcore, bricks and rubble, priced by bag or tonne.",
      "items": [
        {
          "name": "Up to 5 Bags",
          "mins": 30,
          "price": 20
        },
        {
          "name": "Up to 10 Bags",
          "mins": 30,
          "price": 40
        },
        {
          "name": "½ Tonne",
          "mins": 30,
          "price": 50
        },
        {
          "name": "1 Tonne",
          "mins": 60,
          "price": 100
        },
        {
          "name": "2 Tonne",
          "mins": 90,
          "price": 200
        },
        {
          "name": "3 Tonne",
          "mins": 180,
          "price": 300
        }
      ]
    },
    {
      "id": "garden-waste",
      "name": "Garden Waste",
      "blurb": "Green waste, cuttings and soil — by the bag, dumpy bag or van load.",
      "items": [
        {
          "name": "Up to 5 Bags",
          "mins": 20,
          "price": 15
        },
        {
          "name": "Up to 10 Bags",
          "mins": 30,
          "price": 15
        },
        {
          "name": "Dumpy Bag (each)",
          "mins": 30,
          "price": 25
        },
        {
          "name": "Dumpy Bag x4",
          "mins": 30,
          "price": 70
        },
        {
          "name": "¼ Van Load",
          "mins": 30,
          "price": 50
        },
        {
          "name": "½ Van Load",
          "mins": 60,
          "price": 100
        },
        {
          "name": "Full Van Load",
          "mins": 120,
          "price": 200
        }
      ]
    }
  ]
};
